### ISSUE TITLE
Search results not showing after update to 2.0.0 - Error in console

### ISSUE THREAD

**Issue by JosienV92** [algolia/algoliasearch-magento-2#1044]
**Do you want to request a feature or report a bug?**
Report a bug.

**Bug: What is the current behavior?**
The search result page is not showing any results. There is an error in the console: _instantsearch.production.min.js:2 Uncaught TypeError: e is not a function_

**Bug: What is the expected behavior?**
The search result page shows the products found in the search, no errors are in the console

**Bug: What is the proposed solution?**
Find the offending lines of code, determine what goes wrong and, if possible and relevant, look for a way to fix the problem.
 
**Other remarks**

- Magento version is 2.3.5
- AlgoliaSearch version is 2.0.0. Issue arose when updating from v1.13.1
- There were custom changes to AlgoliaSearch in the relevant project, but these are in a separate module. This module was disabled when the issue arose.
- We could not find the relevant file (instantsearch.production.min.js) in the project. 
- As far as we can tell, the issue arises in a function called 'panel', and it goes wrong on the following lines: 
```
var s = n(D({}, e, {
  container: c
}));
```

**Comment by bsuravech** [comment]
Hi @JosienV92! We're sorry to hear you're experiencing some trouble with updating your extension. `instantsearch.production.min.js` is referenced in our `view/frontend/web/internals/algoliaBundle.min.js`. Can you share with us the screenshot of the error printed in the javascript console? This might help us review what is being thrown. 

Let us know! Thanks!

**Comment by edwinbos** [comment]
I work with @JosienV92 on this. Below the screenshots of the error printed in je console.

**The error in the console**

<img width="1440" alt="Screenshot 2020-06-23 at 14 39 37" src="https://user-images.githubusercontent.com/1267356/85404771-bae03d80-b55f-11ea-8181-93576c974c9d.png">

**The (by DevTools) formatted file. The yellow line is where the error occurred**

<img width="1440" alt="Screenshot 2020-06-23 at 14 40 11" src="https://user-images.githubusercontent.com/1267356/85404778-bfa4f180-b55f-11ea-84c7-cb33a409b3e9.png">

**Comment by bsuravech** [comment]
Hi @edwinbos (cc: @JosienV92),

Would it be possible to access this staging environment? We would like to debug the issue on the frontend if possible. 

Additionally, we would like to move this ticket over to our support board. Can you please send an email with the staging link to the issue to [support@algolia.com](mailto:support@algolia.com) and reference this GH issue in it? We will close this issue out here and await your ticket.
